#!/bin/bash

# Цвета
YELLOW='\e[36m'
GREEN='\e[32m'
BLUE='\e[34m'
BOLD='\e[1m'
NC='\e[0m'

difficult(){	# Функция для генерации числа в соответствии с выбранной сложностью
	case $(($1)) in
	"1") local num=$((RANDOM % 10 + 1));;
	"2") local num=$((RANDOM % 100 + 1));;
	"3") local num=$((RANDOM % 2001 - 1000));;
	esac
	echo $(($num))
}

test_input(){  # Проверка числа на нахождение в диапазоне
	local input=$1
	local min=$2
	local max=$3
	if [[ $input -ge $min && $input -le $max ]]; then
		return 0
	fi
	return 1
}

echo
echo -e "${BLUE}-------------${NC}${BOLD}Быки и Коровы${NC}${BLUE}--------------${NC}"  # Приветственный интерфейс
echo -e "${GREEN}Цель игры:${NC} угадать загаданное мной число"
echo ""
echo "Выберите уровень сложности:"
echo -e "1-${GREEN}Низкий${NC}(от 1 до 10)\n2-${GREEN}Средний${NC}(от 1 до 100)\n3-${GREEN}Высокий${NC}(-1000 до 1000)"

while true; do  # Выбор сложности
	read user_choice  # Ввод пользователем (уровень сложности)
	if test_input "$user_choice" "1" "3"; then
		ai_num=$(difficult $user_choice)  # Генерация числа в соответствии с выбранной сложностью
		break
	else
		echo -n "Такой сложности нет! Выберите 1-3:"
	fi
done

attemps=0  # Кол-во попыток
start_time=$(date +%s)

echo -e "${BLUE}------${NC}Игра началась${BLUE}------${NC}"
echo -e "(чтобы выйти введите ${GREEN}stop${NC})"
echo
if [[ $user_choice -eq 1 ]]; then
	min=1
	max=10
elif [[ $user_choice -eq 2 ]]; then
	min=1
	max=100
else
	min=-1000
	max=1000
fi
while true; do
	echo -n "Введите число:"
	read user_try  # Попытка пользователя
	if [[ user_try -eq "stop" ]]; then
		end_time=$(date +%s)
		total_time=$((end_time - start_time))
		echo "Очень жаль =("
		echo -e "Загаданное число: ${YELLOW}$ai_num${NC}"
		break
	fi
	((attemps++))  # +1 в счетчик попыток
	if test_input "$user_try" "$min" "$max"; then
		if [[ $user_try -lt $ai_num ]]; then
			echo -e "Загаданное число ${GREEN}больше${NC}!"
		elif [[ $user_try -gt $ai_num ]]; then
			echo -e "Загаданное число ${GREEN}меньше${NC}!"
		elif [[ $user_try -eq $ai_num ]]; then
			echo
			echo "!!! Поздравляю, вы угадали !!!"
			break
		fi
	else
		echo -e "Ваше число ${GREEN}вне${NC} диапазона =("
	fi
done

end_time=$(date +%s)
total_time=$((end_time - start_time))
echo
echo -e "${YELLOW}=========Статистика=========${NC}"
echo -e "Вы играли ${YELLOW}$total_time${NC} секунд"
echo -e "Колличество попыток: ${YELLOW}$attemps${NC}"
echo -e "${YELLOW}============================${NC}"
